# -*- coding: utf-8 -*-
"""Basic_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WYmO1tGBBmTLplCnfdde6_wDrEoBAnW
"""

# Basic Calculator Program
# Author: [Your Name]
# Description: A simple calculator that performs basic arithmetic operations (+, -, *, /) on two user-input numbers.

def basic_calculator():
    print("Welcome to the Basic Python Calculator!")

    # Get user input
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))
    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return

    # Ask for the operation
    operation = input("Enter an operation (+, -, *, /): ")

    # Perform the selected operation
    if operation == '+':
        result = num1 + num2
        symbol = '+'
    elif operation == '-':
        result = num1 - num2
        symbol = '-'
    elif operation == '*':
        result = num1 * num2
        symbol = '*'
    elif operation == '/':
        if num2 == 0:
            print("Error: Division by zero is undefined.")
            return
        result = num1 / num2
        symbol = '/'
    else:
        print("Invalid operation. Please use one of: +, -, *, /")
        return

    # Display the result
    print(f"{num1} {symbol} {num2} = {result}")

# Run the calculator
basic_calculator()