# -*- coding: utf-8 -*-
"""Custom Class Design

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ma5YDJG9YPb0BDb-hMLuUHcXUEiSATkn

#Assignment : Custom Class Design

## Author: Frederick Ohwoavworiete


This module demonstrates:
1. Class creation with attributes & methods.
2. Constructors for unique object initialization.
3. Inheritance and encapsulation concepts.

### 🏗️ Assignment 1: Design Your Own Class

Here I’ll create a Smartphone class with attributes and methods. Then, I’ll add inheritance and demonstrate encapsulation.
"""

# Base Class
class Smartphone:
    def __init__(self, brand: str, model: str, battery: int):
        """
        Initialize a Smartphone object.

        Args:
            brand (str): The brand of the phone (e.g., Apple, Samsung).
            model (str): The model of the phone.
            battery (int): The current battery percentage (0-100).
        """
        self.brand = brand
        self.model = model
        # Encapsulated attribute
        self.__battery = battery

    def call(self, contact: str) -> str:
        """Simulate making a call."""
        return f"📞 {self.model} is calling {contact}..."

    def charge(self, amount: int) -> None:
        """Charge the battery safely."""
        if amount > 0:
            self.__battery = min(100, self.__battery + amount)

    def get_battery_status(self) -> str:
        """Return battery percentage (encapsulated)."""
        return f"{self.model} battery: {self.__battery}%"

# Inheritance Example
class GamingPhone(Smartphone):
    def __init__(self, brand: str, model: str, battery: int, gpu: str):
        super().__init__(brand, model, battery)
        self.gpu = gpu

    def play_game(self, game: str) -> str:
        """Simulate playing a game on the phone."""
        return f"🎮 Playing {game} on {self.model} with {self.gpu} graphics!"

# Create objects
phone1 = Smartphone("Apple", "iPhone 14", 75)
phone2 = GamingPhone("Asus", "ROG Phone 6", 60, "Adreno 730")

# Use methods
print(phone1.call("Alice"))
print(phone1.get_battery_status())
phone1.charge(20)
print(phone1.get_battery_status())

print(phone2.play_game("PUBG"))
print(phone2.get_battery_status())

"""## 🎭 Activity 2: Polymorphism Challenge

I Will implement polymorphism with different move() methods for vehicles.
"""

class Vehicle:
    def move(self) -> str:
        """Default move behavior (to be overridden)."""
        return "The vehicle moves."

class Car(Vehicle):
    def move(self) -> str:
        return "🚗 The car is driving on the road."

class Plane(Vehicle):
    def move(self) -> str:
        return "✈️ The plane is flying in the sky."

class Boat(Vehicle):
    def move(self) -> str:
        return "🚤 The boat is sailing on water."

# Create a list of different vehicles
vehicles = [Car(), Plane(), Boat()]

# Demonstrate polymorphism
for v in vehicles:
    print(v.move())