# -*- coding: utf-8 -*-
"""Discount Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxhVMBVO9ZDVCw_r8dOATH2eA44le3lI

# Assignment: Discount Calculator
## Author: Frederick Ohwoavworiete
## Platform: Google Colab
## Description:
###   This script defines a function `calculate_discount(price, discount_percent)`that calculates the final price of an item after applying a discount. If the discount is 20% or higher, it applies the discount; otherwise,  it returns the original price.
"""

def calculate_discount(price, discount_percent):
    """
    Calculate the final price after applying a discount.

    Parameters:
        price (float): The original price of the item.
        discount_percent (float): The discount percentage to apply.

    Returns:
        float: The final price after applying the discount if
               discount_percent >= 20, else the original price.
    """
    if discount_percent >= 20:
        discount_amount = (discount_percent / 100) * price
        final_price = price - discount_amount
        return final_price
    else:
        return price


# --- Main Program ---
try:
    # Prompt user for inputs
    original_price = float(input("Enter the original price of the item: "))
    discount_percentage = float(input("Enter the discount percentage: "))

    # Calculate final price using the function
    final_price = calculate_discount(original_price, discount_percentage)

    # Print the result
    if discount_percentage >= 20:
        print(f"Discount applied: {discount_percentage}%")
        print(f"Final Price after discount: {final_price:.2f}")
    else:
        print("Discount less than 20%. No discount applied.")
        print(f"Price remains: {final_price:.2f}")

except ValueError:
    print("Invalid input! Please enter numeric values only.")