# -*- coding: utf-8 -*-
"""File Handling and Exception Handling Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toBL-1Zkvsinr2-T6oifWFJk9janudyI

# File Handling and Exception Handling Assignment
## Author: Frederick Ohwoavworiete
## Description:
### This program demonstrates file reading, writing, and error handling in Python.
"""

from pathlib import Path


def read_and_modify_file(input_file: str, output_file: str) -> None:
    """
    Reads the content of a file, modifies it, and writes the modified
    content to a new file.

    Args:
        input_file (str): Path to the input file.
        output_file (str): Path to the output file.
    """
    try:
        # Read input file
        input_path = Path(input_file)
        if not input_path.exists():
            raise FileNotFoundError(f"The file '{input_file}' does not exist.")

        with input_path.open("r", encoding="utf-8") as file:
            content = file.read()

        # Example modification: convert text to uppercase
        modified_content = content.upper()

        # Write modified content to a new file
        with Path(output_file).open("w", encoding="utf-8") as file:
            file.write(modified_content)

        print(f"✅ Modified content successfully written to '{output_file}'.")

    except FileNotFoundError as e:
        print(f"❌ File Error: {e}")
    except PermissionError:
        print(f"❌ Permission Error: Cannot access '{input_file}' or '{output_file}'.")
    except Exception as e:
        print(f"⚠️ Unexpected Error: {e}")


def main() -> None:
    """
    Main entry point of the program.
    Prompts user for input file and processes it.
    """
    input_filename = input("📂 Enter the name of the file to read: ").strip()
    output_filename = f"modified_{Path(input_filename).name}"

    read_and_modify_file(input_filename, output_filename)


if __name__ == "__main__":
    main()