# -*- coding: utf-8 -*-
"""Ubuntu_Requests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m96p4ZrJim5Ok5jHGTItY8K6VL0VxPe2

# 📜 Assignment Solution: Ubuntu-Inspired Image Fetcher

### Description

This Python script, Ubuntu-Inspired Image Fetcher, embodies the Ubuntu philosophy: "I am because we are." It allows users to connect to the broader internet community, fetch publicly shared images, and organize them neatly in a dedicated folder for later sharing or appreciation.

By combining requests (for fetching resources) and os (for file management), the script ensures:

- Respect for the community by handling errors gracefully 🛡️

- Sharing by saving fetched images into a structured folder 📂

- Practicality by creating a reusable, real-world tool 🌍

✅ Features

- Prompts the user for an image URL 🌐

- Creates a directory Fetched_Images if it doesn’t already exist 📁

- Downloads the image and saves it locally with a meaningful filename 🖼️

- Handles connection issues or invalid URLs gracefully 🙏

- Saves images in binary mode for full fidelity
"""

import os
import requests
from urllib.parse import urlparse

def ubuntu_image_fetcher():
    """
    Ubuntu-Inspired Image Fetcher:
    Fetches an image from a given URL and saves it in a 'Fetched_Images' folder.
    """

    # Prompt user for the image URL
    url = input("🌐 Enter the image URL: ").strip()

    # Create directory for storing images
    folder_name = "Fetched_Images"
    os.makedirs(folder_name, exist_ok=True)

    try:
        # Send HTTP GET request to fetch the image
        response = requests.get(url, stream=True, timeout=10)
        response.raise_for_status()  # Raise an error for HTTP issues

        # Extract filename from the URL
        parsed_url = urlparse(url)
        filename = os.path.basename(parsed_url.path)

        # If no filename in URL, generate a default one
        if not filename:
            filename = "downloaded_image.jpg"

        # Save path
        save_path = os.path.join(folder_name, filename)

        # Save the image in binary mode
        with open(save_path, "wb") as f:
            for chunk in response.iter_content(1024):
                f.write(chunk)

        print(f"✅ Image successfully saved at: {save_path}")

    except requests.exceptions.MissingSchema:
        print("⚠️ Invalid URL format. Please include 'http://' or 'https://'.")
    except requests.exceptions.ConnectionError:
        print("⚠️ Failed to connect. Please check your internet connection.")
    except requests.exceptions.HTTPError as http_err:
        print(f"⚠️ HTTP error occurred: {http_err}")
    except Exception as e:
        print(f"⚠️ An unexpected error occurred: {e}")


# Run the function
if __name__ == "__main__":
    ubuntu_image_fetcher()